

let cardsInfo = [
    {
        id: "jfhgbvnscs",
        title: "Casual Shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-1.jpg",
      },
      {
        id: "ioytrhndcv",
        title: "Office Shirt",
        price: 100,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-2.jpg",
      },
      {
        id: "wuefbncxbsn",
        title: "T Shirt",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-3.jpg",
      },
      {
        id: "thyfhcbcv",
        title: "Mens Suit",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-4.jpg",
      },
      {
        id: "thiecbawdjksadjk",
        title: "Mens Tie",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-5.png",
      },
      {
        id: "iuertrywebncdjksadjk",
        title: "Casual shoes",
        price: 200,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-6.png",
      },
      {
        id: "thierytbvcbvzdhadjk",
        title: "black suit",
        price: 450,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-7.png",
      },
      {
        id: "trfoiwfcnbcawdjksadjk",
        title: "polo shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-8.png",
      },
      {
        id: "cbvxbcvsceldk",
        title: "denim shirt",
        price: 85,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-9.png",
      },
      {
        id: "oiopijmjkhuihb",
        title: "denim pants",
        price: 120,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-10.png",
      },
      {
        id: "oiopijewyiohbjhib",
        title: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-11.png",
      },
      {
        id: "rtytytuyuytyytbvncv",
        title: "leather boots",
        price: 350,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-12.png",
      },
];
